version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    # image: launcher.gcr.io/google/mongodb3
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /mongo:/data/db
